echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 06:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 06:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 06:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 06:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 07:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 07:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 07:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 07:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 08:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 08:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 08:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 08:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 09:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 09:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 09:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 09:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 10:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 10:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 10:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 10:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 11:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 11:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 11:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 11:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 12:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 12:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 12:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 12:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 13:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 13:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 13:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 13:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 14:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 14:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 14:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 14:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 15:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 15:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 15:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 15:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 16:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 16:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 16:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 16:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 17:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 17:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 17:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 17:45
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 18:00
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 18:15
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 18:30
echo "/home/pi/scripts/exe_and_log.sh > /dev/null 2>&1" | at 18:45

